---
# tasks file for dropbox

- name: add dropbox repo key
  apt_key:
    keyserver: pgp.mit.edu
    id: 5044912E
    state: present

- name: Add dropbox repo
  apt_repository:
    repo: deb [arch=i386,amd64] http://linux.dropbox.com/ubuntu wily main
    filename: dropbox

- name: install dependencied
  apt:
    name: python-gpgme

- name: install dropbox
  apt:
    name: dropbox
  notify: restart nautilus